### ISSUE TITLE
Current "progress" indicator

### ISSUE THREAD

**Issue by ShadowLp174** [remix-bot/revolt#138]
keep track of the time that has passed for the song

suggested by @vloddot

**Comment by ShadowLp174** [comment]
found a nice formula on SO: `duration = totalNumPackets * ASBD.mFramesPerPacket / ASBD.mSampleRate`

so to calculate the current duration I just need to find out the frames per packet and keep track of the played packets - _shouldn't be too hard_

**Comment by vloddot** [comment]
Can it be assigned to me? I sort of want to contribute to the bot.

**Comment by ShadowLp174** [comment]
sure lol

**Comment by ShadowLp174** [comment]
@vloddot I just realised this may need modifications to revoice as remix does not work with a certain type of audio streams directly
