### ISSUE TITLE
Global volume control

### ISSUE THREAD

**Issue by shiorid** [remix-bot/revolt#50]
Since there is no volume control in Revolt VoIP itself, it would be fairly useful to have a command like `%volume`.

**Comment by ShadowLp174** [comment]
That is indeed planned, it's just not on this issue tracker, as it will be integrated in revoice.js :)

It is being worked on tho ;)

**Comment by ShadowLp174** [comment]
Oops, I just realised that the issue tracker was private... Made it public :)

**Comment by ShadowLp174** [comment]
Done :D
